# -*- coding: utf-8 -*-
"""Python-otr-1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vL9KM0hGW7u5g1BCCmqWnm1iyXWQAn6W
"""

#this is the first time I am programming from the phone

print('hello world')

nt = list(range(0,40))

for num in nt:
     if num%3 == 0:
         print(num)

[x for x in range(0,9) if x%2==0]

from random import randint

randint(0,99)

from random import shuffle

mylist = [1,2,56,45,76,78,9,65,69,34]


shuffle(mylist)

mylist

max(mylist)

[num for num in mylist if num%2==0]

min(mylist)

t = list(enumerate('abcde'))

t

for a,b in t:
     print(a)
     print(b)

num = list(range(0,30))

for numbers in num:
      if numbers%2==0:
             print(numbers)